platform :ios, '10.0'
use_frameworks!

target 'ios-itunes-search' do

  pod 'Alamofire', '4.5.1'
  pod 'ObjectMapper', '3.0.0'
  pod 'SVProgressHUD', '2.2.1'
  pod 'RealmSwift', '2.10.1'

  target 'ios-itunes-searchTests' do
    inherit! :search_paths
  end

end
